package writer

import (
	"bytes"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"reqmd-import/internal/model"
)

// Note: model.GeneratedReq and model.Symbol are defined by Fixer A's
// skeleton (internal/model/doc.go). The expected field shape used by the
// renderer is:
//
//	type Symbol struct {
//	    Name     string
//	    Kind     string  // "struct" | "method" | "func" | "const" | "var" | "type"
//	    Package  string
//	    Receiver string  // for methods, the receiver type name
//	}
//
//	type GeneratedReq struct {
//	    ID               string
//	    Title            string
//	    Status           string
//	    Version          string
//	    Disposition      string
//	    DispositionReason string
//	    Body             string
//	    SourceFile       string
//	    SourceLine       int
//	    SymbolKind       string
//	    ParentID         string
//	    Trace            []string
//	    Symbol           model.Symbol
//	}
//
// If those fields drift, the renderer breaks loudly at compile time — that
// is intentional.

func TestRenderPackageMD(t *testing.T) {
	pkg := Package{
		Name: "foo",
		Reqs: []model.GeneratedReq{
			{
				ID:     "IMP-foo-StructA-abc1234",
				Title:  "StructA",
				Status: "approved",
				Body:   "StructA description from godoc.",
				Symbol: model.Symbol{Name: "StructA", Kind: "struct", Package: "foo"},
			},
			{
				ID:       "IMP-foo-StructA-Method1-xyz5678",
				Title:    "Method1",
				Status:   "approved",
				ParentID: "IMP-foo-StructA-abc1234",
				Body:     "Method1 description from godoc.",
				Symbol:   model.Symbol{Name: "Method1", Kind: "method", Package: "foo", Receiver: "StructA"},
			},
			{
				ID:       "IMP-foo-StructA-Method2-zzz9999",
				Title:    "Method2",
				Status:   "approved",
				ParentID: "IMP-foo-StructA-abc1234",
				Body:     "Method2 description from godoc.",
				Symbol:   model.Symbol{Name: "Method2", Kind: "method", Package: "foo", Receiver: "StructA"},
			},
			{
				ID:     "IMP-foo-FuncB-def9012",
				Title:  "FuncB",
				Status: "approved",
				Body:   "FuncB description from godoc.",
				Symbol: model.Symbol{Name: "FuncB", Kind: "func", Package: "foo"},
			},
		},
	}
	out := RenderPackageMD(pkg)

	checks := []struct {
		name string
		want string
	}{
		{"package title", "# Package: foo"},
		{"auto-gen marker", GeneratedMarker},
		{"auto-gen notice", "This file is auto-generated by reqmd-import."},
		{"top-level struct heading", "## IMP-foo-StructA-abc1234: StructA"},
		{"top-level func heading", "## IMP-foo-FuncB-def9012: FuncB"},
		{"nested method1 heading", "### IMP-foo-StructA-Method1-xyz5678: Method1"},
		{"nested method2 heading", "### IMP-foo-StructA-Method2-zzz9999: Method2"},
		{"imported marker in attr", "x-reqmd.imported: true"},
		{"status key", "status: approved"},
		{"empty trace", "trace: []"},
		{"attr block fence", "```attr"},
		{"struct body", "StructA description from godoc."},
		{"method1 body", "Method1 description from godoc."},
		{"func body", "FuncB description from godoc."},
	}
	for _, c := range checks {
		if !strings.Contains(out, c.want) {
			t.Errorf("missing %q in rendered output", c.want)
		}
	}
}

func TestRenderRequirementHeadingDepth(t *testing.T) {
	top := model.GeneratedReq{
		ID:     "IMP-bar-Const-c0nst",
		Title:  "Const",
		Status: "approved",
		Symbol: model.Symbol{Name: "Const", Kind: "const", Package: "bar"},
	}
	child := model.GeneratedReq{
		ID:       "IMP-bar-Const-Sub-sub0",
		Title:    "Sub",
		Status:   "approved",
		ParentID: "IMP-bar-Const-c0nst",
		Symbol:   model.Symbol{Name: "Sub", Kind: "const", Package: "bar"},
	}

	topOut := RenderRequirement(top)
	if !strings.HasPrefix(topOut, "## IMP-bar-Const-c0nst") {
		t.Errorf("top-level requirement should use ##, got: %q", firstLine(topOut))
	}

	childOut := RenderRequirement(child)
	if !strings.HasPrefix(childOut, "### IMP-bar-Const-Sub-sub0") {
		t.Errorf("child requirement should use ###, got: %q", firstLine(childOut))
	}
}

func TestIsGenerated(t *testing.T) {
	if !IsGenerated([]byte("# hi\n" + GeneratedMarker + "\nbody")) {
		t.Error("expected IsGenerated=true for content with marker")
	}
	if IsGenerated([]byte("# hi\nno marker here")) {
		t.Error("expected IsGenerated=false for content without marker")
	}
	if IsGenerated(nil) {
		t.Error("expected IsGenerated=false for nil content")
	}
}

func TestPackage_OrderIndependentFromInput(t *testing.T) {
	// Children passed before parent should still render under their parent,
	// and stable sort means repeated calls produce identical output.
	pkg := Package{
		Name: "ord",
		Reqs: []model.GeneratedReq{
			{
				ID:       "IMP-ord-A-m1",
				Title:    "M1",
				Status:   "approved",
				ParentID: "IMP-ord-A-aaaa",
				Symbol:   model.Symbol{Name: "M1", Kind: "method", Package: "ord", Receiver: "A"},
			},
			{
				ID:     "IMP-ord-A-aaaa",
				Title:  "A",
				Status: "approved",
				Symbol: model.Symbol{Name: "A", Kind: "struct", Package: "ord"},
			},
		},
	}
	first := RenderPackageMD(pkg)
	second := RenderPackageMD(pkg)
	if first != second {
		t.Error("RenderPackageMD must be deterministic across calls")
	}
	if !strings.Contains(first, "## IMP-ord-A-aaaa: A\n") {
		t.Error("parent heading should come before child heading")
	}
	parentIdx := strings.Index(first, "## IMP-ord-A-aaaa: A")
	childIdx := strings.Index(first, "### IMP-ord-A-m1: M1")
	if parentIdx < 0 || childIdx < 0 || parentIdx > childIdx {
		t.Errorf("expected parent (%d) before child (%d)", parentIdx, childIdx)
	}
}

// TestWriteTargetIdempotent verifies that a second WriteTarget call on the
// same directory produces byte-identical files (the idempotency contract
// that the writeIfChanged path depends on). This is the regression test
// for the schema write-once bug: if the writer's own schema output lacks
// the generated marker, the second run would skip the write and the file
// would diverge from the writer's intent.
func TestWriteTargetIdempotent(t *testing.T) {
	tmp := t.TempDir()
	packages := []Package{{Name: "p", Reqs: []model.GeneratedReq{{ID: "IMP-p-X-aaaaaaa", Title: "X", Status: "approved"}}}}
	if err := WriteTarget(tmp, packages, "IMP-"); err != nil {
		t.Fatalf("first WriteTarget: %v", err)
	}
	first, err := readAllYAMLAndMD(t, tmp)
	if err != nil {
		t.Fatalf("read first: %v", err)
	}
	if err := WriteTarget(tmp, packages, "IMP-"); err != nil {
		t.Fatalf("second WriteTarget: %v", err)
	}
	second, err := readAllYAMLAndMD(t, tmp)
	if err != nil {
		t.Fatalf("read second: %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Errorf("WriteTarget not idempotent:\nfirst:\n%s\nsecond:\n%s", first, second)
	}
}

// TestWriteTargetDoesNotClobberHandAuthored verifies that a hand-authored
// schema.yaml (no generated marker) is left untouched on a second run.
func TestWriteTargetDoesNotClobberHandAuthored(t *testing.T) {
	tmp := t.TempDir()
	if err := os.MkdirAll(tmp, 0o755); err != nil {
		t.Fatal(err)
	}
	handAuthored := "# hand-authored schema\nstatus: draft\n"
	if err := os.WriteFile(filepath.Join(tmp, "schema.yaml"), []byte(handAuthored), 0o644); err != nil {
		t.Fatal(err)
	}
	packages := []Package{{Name: "p", Reqs: []model.GeneratedReq{{ID: "IMP-p-X-aaaaaaa", Title: "X", Status: "approved"}}}}
	if err := WriteTarget(tmp, packages, "IMP-"); err != nil {
		t.Fatalf("WriteTarget: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(tmp, "schema.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != handAuthored {
		t.Errorf("hand-authored schema was clobbered:\nwant:\n%s\ngot:\n%s", handAuthored, got)
	}
}

// readAllYAMLAndMD reads every .yaml and .md file under dir into a single
// byte slice in a stable order, for idempotency comparison.
func readAllYAMLAndMD(t *testing.T, dir string) ([]byte, error) {
	t.Helper()
	var paths []string
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if ext := filepath.Ext(path); ext == ".yaml" || ext == ".md" {
			paths = append(paths, path)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)
	var out []byte
	for _, p := range paths {
		data, err := os.ReadFile(p)
		if err != nil {
			return nil, err
		}
		out = append(out, data...)
		out = append(out, '\n')
	}
	return out, nil
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}

func TestRenderRequirementHeuristicTrace(t *testing.T) {
	req := model.GeneratedReq{
		ID:             "IMP-foo-Bar-1234567",
		Title:          "Bar",
		Status:         "approved",
		Trace:          []string{"REQ-AUTH-001"},                 // explicit
		HeuristicTrace: []string{"REQ-LOG-002", "SYS-LOGIN-007"}, // heuristic
		Symbol:         model.Symbol{Name: "Bar", Kind: "function", Package: "foo"},
	}
	out := RenderRequirement(req)

	// Explicit trace renders first
	if !strings.Contains(out, "trace:\n  - REQ-AUTH-001") {
		t.Error("explicit trace not rendered correctly")
	}
	// Heuristic trace renders in a separate attribute, after `trace:`
	if !strings.Contains(out, "x-reqmd.heuristic-trace:\n  - REQ-LOG-002\n  - SYS-LOGIN-007") {
		t.Errorf("heuristic trace not rendered correctly in output:\n%s", out)
	}
	// Order check: explicit `trace:` should appear before `x-reqmd.heuristic-trace:`
	if strings.Index(out, "trace:") > strings.Index(out, "x-reqmd.heuristic-trace:") {
		t.Error("trace: should appear before x-reqmd.heuristic-trace:")
	}
}

func TestRenderRequirementNoHeuristicTrace(t *testing.T) {
	// When HeuristicTrace is empty, the attribute should be omitted entirely.
	req := model.GeneratedReq{
		ID:     "IMP-foo-Baz-7654321",
		Title:  "Baz",
		Status: "approved",
		Trace:  []string{"REQ-001"},
		Symbol: model.Symbol{Name: "Baz", Kind: "function", Package: "foo"},
	}
	out := RenderRequirement(req)
	if strings.Contains(out, "heuristic-trace") {
		t.Errorf("empty HeuristicTrace should be omitted; got:\n%s", out)
	}
}

func TestWriteTargetPerPackagePrefix(t *testing.T) {
	tmp := t.TempDir()
	packages := []Package{
		{
			Name: "arith",
			Reqs: []model.GeneratedReq{
				{
					ID:     "IMP-arith-add-16962f2",
					Title:  "add",
					Status: "approved",
					Symbol: model.Symbol{Name: "add", Kind: "func", Package: "arith"},
				},
			},
		},
		{
			Name: "cli",
			Reqs: []model.GeneratedReq{
				{
					ID:     "IMP-cli-Run-deadbe",
					Title:  "Run",
					Status: "approved",
					Symbol: model.Symbol{Name: "Run", Kind: "func", Package: "cli"},
				},
			},
		},
	}
	if err := WriteTarget(tmp, packages, "IMP-"); err != nil {
		t.Fatalf("WriteTarget: %v", err)
	}

	// Each per-package schema should declare a unique, package-specific
	// prefix derived from the global --id-prefix flag + package name.
	arithSchema, err := os.ReadFile(filepath.Join(tmp, "arith", "schema.yaml"))
	if err != nil {
		t.Fatalf("read arith schema: %v", err)
	}
	if !strings.Contains(string(arithSchema), `id-prefix: IMP-arith-`) {
		t.Errorf("arith schema missing per-package prefix IMP-arith-; got:\n%s", arithSchema)
	}

	cliSchema, err := os.ReadFile(filepath.Join(tmp, "cli", "schema.yaml"))
	if err != nil {
		t.Fatalf("read cli schema: %v", err)
	}
	if !strings.Contains(string(cliSchema), `id-prefix: IMP-cli-`) {
		t.Errorf("cli schema missing per-package prefix IMP-cli-; got:\n%s", cliSchema)
	}

	// Top-level schema keeps the original (no per-package override).
	topSchema, err := os.ReadFile(filepath.Join(tmp, "schema.yaml"))
	if err != nil {
		t.Fatalf("read top-level schema: %v", err)
	}
	if !strings.Contains(string(topSchema), `id-prefix: "IMP-"`) {
		t.Errorf("top-level schema lost its default prefix IMP-; got:\n%s", topSchema)
	}

	// No per-package schema should still carry the bare "IMP-" prefix —
	// that is exactly the regression we are fixing.
	if strings.Contains(string(arithSchema), `id-prefix: IMP-`) && !strings.Contains(string(arithSchema), `id-prefix: IMP-arith-`) {
		t.Error("arith schema still declares the bare IMP- prefix (would collide)")
	}
	if strings.Contains(string(cliSchema), `id-prefix: IMP-`) && !strings.Contains(string(cliSchema), `id-prefix: IMP-cli-`) {
		t.Error("cli schema still declares the bare IMP- prefix (would collide)")
	}

	// Sanity: a custom --id-prefix flows through end-to-end.
	tmp2 := t.TempDir()
	if err := WriteTarget(tmp2, []Package{
		{
			Name: "foo",
			Reqs: []model.GeneratedReq{{ID: "MY-foo-X-1234567", Status: "approved"}},
		},
	}, "MY-"); err != nil {
		t.Fatalf("WriteTarget (custom prefix): %v", err)
	}
	fooSchema, err := os.ReadFile(filepath.Join(tmp2, "foo", "schema.yaml"))
	if err != nil {
		t.Fatalf("read foo schema: %v", err)
	}
	if !strings.Contains(string(fooSchema), `id-prefix: MY-foo-`) {
		t.Errorf("custom id-prefix did not flow through; got:\n%s", fooSchema)
	}
}

func TestQuoteIfNeeded(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		// Empty string: must quote (so `key: ` does not collapse to null).
		{"empty", "", `""`},
		// Plain values: pass through unquoted.
		{"plain", "foo", "foo"},
		{"plain path", "/tmp/source.go", "/tmp/source.go"},
		{"plain symbol kind", "function", "function"},
		// Characters that confuse YAML flow scalars.
		{"colon", "weird:name", `"weird:name"`},
		{"hash", "weird # comment", `"weird # comment"`},
		{"double quote", `say "hi"`, `"say \"hi\""`},
		{"single quote", "it's fine", `"it's fine"`},
		{"newline mid", "line1\nline2", `"line1\nline2"`},
		{"tab mid", "col1\tcol2", `"col1\tcol2"`},
		// Leading/trailing whitespace and YAML list markers.
		{"leading space", " foo", `" foo"`},
		{"trailing space", "foo ", `"foo "`},
		{"leading tab", "\tfoo", `"\tfoo"`},
		{"leading dash", "-foo", `"-foo"`},
		{"leading star", "*foo", `"*foo"`},
		// Backslash must be escaped.
		{"backslash", `C:\Users\foo`, `"C:\\Users\\foo"`},
		// Windows path with colon AND backslash.
		{"windows path", `C:\Users\foo\bar.go`, `"C:\\Users\\foo\\bar.go"`},
		// Combined: a real on-disk path that contains a colon.
		{"path with colon", "/tmp/weird:dir/file.go", `"/tmp/weird:dir/file.go"`},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := quoteIfNeeded(c.in)
			if got != c.want {
				t.Errorf("quoteIfNeeded(%q) = %q, want %q", c.in, got, c.want)
			}
		})
	}
}

// TestQuoteIfNeededRoundTrip verifies that values containing YAML-special
// characters (newlines, tabs, quotes, backslashes) survive a round-trip
// through a YAML parser unchanged. This is the regression test for the
// earlier bug where \n and \t were not escaped, causing YAML to fold the
// line break to a space.
func TestQuoteIfNeededRoundTrip(t *testing.T) {
	cases := []string{
		"line1\nline2",
		"col1\tcol2",
		"col1\ncol2\tcol3",
		"say \"hi\"",
		`C:\Users\foo`,
		"normal",
		"",
		`weird: "value" with \backslash`,
	}
	for _, in := range cases {
		t.Run(in, func(t *testing.T) {
			quoted := quoteIfNeeded(in)
			var out any
			if err := yaml.Unmarshal([]byte(quoted), &out); err != nil {
				t.Fatalf("yaml.Unmarshal(%q): %v", quoted, err)
			}
			if out != in {
				t.Errorf("round-trip lost data: in=%q out=%v", in, out)
			}
		})
	}
}
